export const STATUS = {
  OK: 200,
  CREATED: 201,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500
};

export const BINDER_AUTHORITY_LEVEL = {
  GUEST: 0,
  MAINTAINER: 10,
  OWNER: 50,
};